/*
 * Copyright 2011 Xavier de Gaye
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package vimoir.netbeans;

/**
 * The interface methods are call back methods that map to Netbeans events.
 */
public interface NetbeansEventHandler {

    //-----------------------------------------------------------------------
    //   Events
    //-----------------------------------------------------------------------

    /**
     * Process a <code>startupDone</code> Netbeans event.
     *
     * <p> Vim has finished its startup work and is ready for editing files.
     */
    public void event_startupDone();

    /**
     * Process a <code>disconnect</code> Netbeans event.
     *
     * <p> Vim is exiting, the client must not write more commands.
     */
    public void event_disconnect();

    /**
     * Process a <code>fileOpened</code> Netbeans event.
     *
     * <p> A file was opened by the Vim user.
     *
     * @param buf the buffer instance
     */
    public void event_fileOpened(NetbeansBuffer buf);

    /**
     * Process a <code>killed</code> Netbeans event.
     *
     * <p> A file was deleted or wiped out by the Vim user and the buffer
     * annotations have been removed.  The buffer is not registered anymore.
     *
     * @param buf the buffer instance
     */
    public void event_killed(NetbeansBuffer buf);

    /**
     * Process a timer event.
     */
    public void event_tick();

    /**
     * Process an error message generated by the Netbeans socket.
     *
     * @param message the error message
     */
    public void event_error(String message);

    //-----------------------------------------------------------------------
    //   Commands
    //-----------------------------------------------------------------------

    /**
     * The default method invoked by the Netbeans socket on a <code>keyAtPos</code>
     * Netbeans event.
     *
     * <p>The Netbeans socket falls back to invoking this method when the
     * NetbeansEventHandler object does not implement the
     * <code>cmd_keyName</code> method, <code>keyName</code> being the first
     * token of the Vim <code>:nbkey</code> command.
     *
     * @param keyName  the first parameter of Vim <code>:nbkey</code> command
     * @param args     the remaining string in the <code>:nbkey</code> command
     * @param buf      the buffer instance
     */
    public void default_cmd_processing(String keyName, String args, NetbeansBuffer buf);
}
